version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:10-browsers
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm run lint
            - run: npm run jest:ci
            - run: npm run test:ci
            - run: npm run e2e:ci
            - run: npm run build
workflows:
    build-and-test:
      jobs:
        - build-and-test